name: mahasiswa_crud_app
description: Aplikasi Flutter CRUD Mahasiswa dengan SQLite dan Provider
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.3.2
  path: ^1.9.0
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true